version: '3.9'
services:
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.5.7
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    ports:
      - "9092:9092"
  zookeeper:
    container_name: zookeeper
    restart: always
    image: confluentinc/cp-zookeeper:5.5.7
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-network

networks:
  kafka-network:
#TODO: configure secured kafka connection, configure replicas